# Generated by Django 4.1.5 on 2023-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
